### ISSUE TITLE
Incorrect currency pattern in uk.json

### ISSUE THREAD

**Issue by ifuller1** [andyearnshaw/Intl.js#102]
Hi,

https://github.com/andyearnshaw/Intl.js/blob/f5ab43f764d6cf1be61731f7c57b325ac4c2b6d6/locale-data/json/uk.json#L2148 shows a currency format for the UK which puts the currency symbol after the value. I believe it should be other other way around.

On ES5 browsers the result of 

`(new Intl.NumberFormat('en-UK', {style:'currency', currency:'GBP'})).format(0)` is `£0`

Falling back to Intl.js the result is

`(new Intl.NumberFormat('en-UK', {style:'currency', currency:'GBP'})).format(0)` is `0,00 £`

If you could confirm my understanding of this I'll raise a PR to change it.

Ian

**Comment by andyearnshaw** [comment]
`en-UK` isn't a supported CLDR locale, you probably meant `en-GB` (British English). If you're including `uk.json` data but not `en-GB.json` or `en.json`, it's probably falling back to `uk` (Ukranian) instead.

**Comment by ifuller1** [comment]
That's for the clarification, you're quite right that uk isn't valid!

Should the implementation be consistent with ES5 though?

**Comment by ifuller1** [comment]
I actually see that we were only including uk in our build - thanks for the feedback.

Ian
