### ISSUE TITLE
1.0.0-rc-1 Fails in IE8

### ISSUE THREAD

**Issue by ollym** [andyearnshaw/Intl.js#106]
```javascript
new Intl.DateTimeFormat('en-US', { weekday: 'short' }).format(new Date);
```

Expected output `Tue` or `Wed` or whenever you try this out.

In IE8 on XP, it returns `undefined`

Similarly i'd expect the following:

```javascript
new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(new Date);
```

To return something like `June 2015`

Instead in IE8 it returns `2015 2015`

**Comment by caridy** [comment]
cool, thanks @ollym, we need a warrior to take on this one jejeje.

**Comment by ollym** [comment]
Just to help debug, the following:

```javascript
new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).resolvedOptions()
```

Returns:

IE8 on XP

```json
{
  "locale": "en-US",
  "calendar": "gregory",
  "numberingSystem": "latn",
  "year": "numeric",
  "month": "short"
}
```
And on Chrome:

```json
{
  "locale": "en-US",
  "calendar": "gregory",
  "numberingSystem": "latn",
  "timeZone": "Europe/London",
  "year": "numeric",
  "month": "long"
}
```

Clearly the month value is wrong. Not sure whether this is part of the cause.

**Comment by andyearnshaw** [comment]
I've checked this out on IE11 in IE8 compat mode.  I had to make a small fix (see ie8-fix branch), but everything seems OK.  I'll see if I can get on sauce labs for a more genuine browser check.

**Comment by caridy** [comment]
@ollym can you give it a try with intl@1.0.0-rc-4?

**Comment by ollym** [comment]
@caridy sorry for the delays here, IE8 is working again now (using master/rc4)

**Comment by caridy** [comment]
excellent.
