### ISSUE TITLE
release 1.0 checklist

### ISSUE THREAD

**Issue by caridy** [andyearnshaw/Intl.js#122]
* [x] local unit tests
* [x] travis
* [x] docs (readme)
* [x] publish
* [x] release notes
* [x] sanity check

**Comment by caridy** [comment]
total 106 -- passed 106 -- failed 0

**Comment by caridy** [comment]
Readme: https://github.com/andyearnshaw/Intl.js/commit/30cb2c40fe348b42e285b8dbd4b9d9bfab32c15d

**Comment by caridy** [comment]
published: `+ intl@1.0.0`

**Comment by caridy** [comment]
Release notes: https://github.com/andyearnshaw/Intl.js/releases/tag/1.0.0

**Comment by caridy** [comment]
Alright guys (@Turbo87, @ollym, @okuryu, @kate2753 @mweibel, @andyearnshaw @ericf and @juandopazo), I finally get a change to release 1.0.0 in preparation for the FT polyfill service. There are still edge cases and bugfixes, but I didn't want to keep delaying the release, let's roll with it, and lets fix those issues when we get a chance! Thanks again for all the help.

**Comment by okuryu** [comment]
:+1:

**Comment by andyearnshaw** [comment]
Great work, @caridy, thanks!
