### ISSUE TITLE
cannot specify maximumFractionDigits < 2 without also setting minimumFractionDigits

### ISSUE THREAD

**Issue by jasonmit** [andyearnshaw/Intl.js#123]
https://github.com/yahoo/ember-intl/issues/167

It appears you need to pass a `maximumFractionDigits` and a `minimumFractionDigits` when dealing with the polyfill.

```js
// works

var Intl = require('intl');
new Intl.NumberFormat("en", { 
  maximumFractionDigits: 0, 
  minimumFractionDigits: 0, 
  style: 'currency', 
  currency: 'USD'
}).format(4000.33)
```

```js
// throws with RangeError('Value is not a number or outside accepted range')

var Intl = require('intl');
new Intl.NumberFormat("en", { 
  maximumFractionDigits: 0, 
  style: 'currency', 
  currency: 'USD'
}).format(4000.33)
```

My sad attempt at triaging with what I feel is happening.

```js
var value = options[property]; // property='maximumFractionDigits'

// this condition line does not appear correct.
// it's validating the maximumFractionDigits option value, 0,
// against the minimum defaults to 2 and the maximum
// default is 20 so this condition is truthy and
// maximumFractionDigits is perceived as being out of range
if (isNaN(value) || value < minimum || value > maximum)
   throw new RangeError('Value is not a number or outside accepted range');
```

The function in question: https://github.com/andyearnshaw/Intl.js/blob/master/src/core.js#L955-L976

It's entirely possible that the spec was implemented correctly in the Polyfill and not correctly implemented in the browser API.

/cc @caridy

**Comment by andyearnshaw** [comment]
We're just following the spec here.  The relevant part of the spec is section in 11.1.1:

> 30\. If s is "currency", let mnfdDefault be cDigits; else let mnfdDefault be 0.
> 31. Let mnfd be GetNumberOption(options, "minimumFractionDigits", 0, 20, mnfdDefault).
> 32. ReturnIfAbrupt(mnfd).
> 33. Set numberFormat.[[minimumFractionDigits]] to mnfd.
> 34. If s is "currency", let mxfdDefault be max(mnfd, cDigits); else if s is "percent", let mxfdDefault be max(mnfd, 0); else let mxfdDefault be max(mnfd, 3).
> 35. Let mxfd be GetNumberOption(options, "maximumFractionDigits", mnfd, 20, mxfdDefault).

So because _minimumFractionDigits_ isn't specified and the style is `'currency'`, _mnfd_ defaults to `2`.  Then, in _GetNumberOption_, 9.2.10:

> [6]. If value is NaN or less than minimum or greater than maximum, throw a RangeError exception. 
> [7]. Else return fallback.

_mxfd_ (the specified value) is less than _mnfd_ (the minimum permitted value) and the _RangeError_ is thrown.

FWIW Chrome doesn't throw, but Firefox does.  I haven't checked Internet Explorer but we won't change this unless it changes in the spec.

**Comment by jasonmit** [comment]
:+1: thanks for looking into this

**Comment by Sunyang730** [comment]
Safari also throw an error

**Comment by awolfson** [comment]
Just want to note here that it appears Chrome 59 now throws this error also.

**Comment by mkurczewski** [comment]
So it's a simple as
```
minimumFractionDigits: 0,
maximumFractionDigits: 0,
```
