### ISSUE TITLE
No support for weekday: 'long'

### ISSUE THREAD

**Issue by jwdallas** [andyearnshaw/Intl.js#125]
Hello, I’m unable to get the 'long' version of the weekday. It seems that is not currently supported from my test here:
![screen shot 2015-07-14 at 12 48 48 pm](https://cloud.githubusercontent.com/assets/1310725/8683295/b4aaec7c-2a26-11e5-85ab-4981d46fb50f.png)
http://jsbin.com/lotaseyebu/1/edit?html,console

Results:
“Tue”

Expected:
“Tuesday”

This is likely related to https://github.com/andyearnshaw/Intl.js/issues/117 and https://github.com/andyearnshaw/Intl.js/issues/124.

**Comment by caridy** [comment]
Fixed by PR #146, shipped in intl@1.1.0
