### ISSUE TITLE
Grammar error of Chinese datetime

### ISSUE THREAD

**Issue by learning** [andyearnshaw/Intl.js#136]
Grammar error of Chinese datetime

```javascript
new Intl.DateTimeFormat('zh-CN', {
  month: 'narrow',
  day: 'numeric'
}).format(new Date('2016-10-19'))
```

output: `10月月19日`
expect: `10月19日`

[http://codepen.io/anon/pen/WQrVYM](http://codepen.io/anon/pen/WQrVYM)

**Comment by okuryu** [comment]
Yes, this is a known issue. See #69.

**Comment by caridy** [comment]
closing in favor of #69

**Comment by okuryu** [comment]
@caridy Could you reopen #69?
