### ISSUE TITLE
Expected Identifier error in IE8

### ISSUE THREAD

**Issue by donnrri** [andyearnshaw/Intl.js#137]
Hello,

I am loading Intl.js conditionally when Intl is not supported . However when I test in IE8 I get a 'expected identifier' error .

The line it fails at appears to be:

val("/* WEBPACK VAR INJECTION */(function(global) {var m =__webpack_require__(474),\n   IntlPolyfill = m.default;\n\n// Expose`IntlPolyfill` as global to add locale data into runtime later on.\

Does any one have any advice on how to resolve this very cryptic error ? Seems webpack is having a problem exposing the global Intl .

Any help much appreciated as I have to internationalise an app in IE8

**Comment by caridy** [comment]
You should probably look into using the polyfill service to avoid the hazard of using polyfills with webpack.
