### ISSUE TITLE
*.js.map files are not packaged into NPM

### ISSUE THREAD

**Issue by zivl** [andyearnshaw/Intl.js#154]
Hi,

I'm using `intl@1.1.0` and I get the following warning when I load the files (I'm using `webpack`):
```
./~/intl/lib/core.js
Cannot find SourceMap 'core.js.map': Error: Cannot resolve 'file' or 'directory' ./core.js.map in <path_to_my_project>\node_modules\intl\lib
```

After a few checks, I saw that you do not include the `sourceMaps` files in the package.
You should either delete the `sourceMap` reference from the `.js` files or include them in the `npm` package.

Also, I get the same warnings for other `intl` based plug-ins such as `intl-messageformat@1.3.0`

Cheers

**Comment by danilobuerger** [comment]
+1

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/issues/171

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.1
