### ISSUE TITLE
problem of date format in ja-JP

### ISSUE THREAD

**Issue by kinglywork** [andyearnshaw/Intl.js#164]
**Code:**
```
  const IntlPolyfill = require('intl');
  DateTimeFormat = IntlPolyfill.DateTimeFormat;
  require('intl/locale-data/jsonp/ja');

console.log(
  new DateTimeFormat('ja-JP-u-ca-japanese', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    era: 'short'
}).format(Date.now()));
```

**Expect:**
平成28年4月21日
**But:**
12016年4月月21日

**Version:**
1.1.0

**PS.**
this works fine
`DateTimeFormat = global.Intl.DateTimeFormat;`

**Comment by okuryu** [comment]
This might be related with #69.

**Comment by caridy** [comment]
yeah, I have struggled with this for a long time, need time to regroup on those issues.

**Comment by watilde** [comment]
This issue should be separated as a year part for an era and a month part for the known issue.
> 12016年4月月21日

In the era part, the point in code seems `TODO` and I tried to add a case for it, eventually it worked: https://github.com/andyearnshaw/Intl.js/pull/166
> 西暦2016年4月月25日
