### ISSUE TITLE
Number formatting for Indian numbers

### ISSUE THREAD

**Issue by devang-kredx** [andyearnshaw/Intl.js#165]
India and a few other countries have number like ##,##,##0.### (thousands/lakhs/crores). However, using locale as "en-IN" still gives the grouping of digits as ###,###,##0.###.
This issue was references and solves in https://github.com/andyearnshaw/Intl.js/issues/51 but its sill not working for me. I am using `react-intl`.

**Comment by caridy** [comment]
when I tried this in a browser (chrome), this is what I see:

```
new Intl.NumberFormat('en-IN').format(123445667)
"123,445,667"
```
 
while inspecting the resolved options:

```
new Intl.NumberFormat('en-IN').resolvedOptions()
Object {locale: "en", numberingSystem: "latn", style: "decimal", useGrouping: true, minimumIntegerDigits: 1…}
```

`en-IN` is not supported by chrome.

**Comment by watilde** [comment]
I just tried the issue case and I could see `11,22,333.444` correctly. Is this issue still happening?
```html
<html>
  <body>
    <script src="dist/Intl.js"></script>
    <script src="locale-data/jsonp/en-IN.js"></script>
    <script>
      console.log(new IntlPolyfill.NumberFormat('en-IN').format(1122333.444));
      // => 11,22,333.444
    </script>
  </body>
</html>
```

**Comment by devang-kredx** [comment]
Did you try it in Chrome, this seems to be Chrome related issue which
doesn't support en-IN.

**Comment by watilde** [comment]
@devang-kredx Hello! I've tried on Chrome and Safari. Now I just tried `IntlPolyfill` and native `Intl` object as well on Chrome again. Either way it worked for me.
```js
console.log(new Intl.NumberFormat('en-IN').format(1122333.444));
// => 11,22,333.444
console.log(new IntlPolyfill.NumberFormat('en-IN').format(1122333.444));
// => 11,22,333.444
```
Browser versions:
+ Chrome: 51.0.2704.84 (64-bit)
+ Safari: 9.1 (11601.5.17.1)

**Comment by devang-kredx** [comment]
Interesting. I am using it through react-intl and it's formatting incorrectly in that case. Closing the issue here and will try to debug react-intl.

**Comment by caridy** [comment]
@devang-kredx make sure you're using the latest version, that might be it.
