### ISSUE TITLE
NumberFormat should use commercial roundoff 

### ISSUE THREAD

**Issue by iilei** [andyearnshaw/Intl.js#168]
As `0.5` results in  `1` using the default `Math.round`, I would expect `0.015` to be turned into `0.02`. The native implementation in Chrome is doing exactly that.

However, the polyfill rounds it to `0.01`: 

```js
const numberFormat = Intl.NumberFormat('de-DE', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
});

numberFormat(0.015); // expected: 0.02 - actual: 0.01 
```

**Comment by watilde** [comment]
This issue was fixed by https://github.com/andyearnshaw/Intl.js/pull/169 🎉 
```js
console.log(
  IntlPolyfill.NumberFormat('de-DE', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  }).format(0.015)
)
// => 0,02
```

**Comment by iilei** [comment]
Using v1.2.1 I get `"0,020,02"` (or, for `en-GB`, `"0.020.02"`) 😞 

My setup incorporates npm, webpack and babel. If needed I could provide you with a setup boiled down to the relevant packages but I assume this can be easily reproduced.

**Comment by watilde** [comment]
Oh really, sorry let me check it again on Safari. I should use it at first instead of Chrome...

This issue seems same to https://github.com/andyearnshaw/Intl.js/issues/176. I just tried with https://github.com/andyearnshaw/Intl.js/pull/177 patch and it worked correctly.

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/pull/177
