### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by caridy** [andyearnshaw/Intl.js#171]
* [x] npm publish (https://www.npmjs.com/package/intl)
 * [x] PR on FT polyfill service (https://github.com/Financial-Times/polyfill-service/pull/699)
 * [x] release notes (https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.1)
 * [x] bower update
 * [x] tag (v1.2.1)

**Comment by yoni-tock** [comment]
Are y'all already aware that this broke in Safari?

<img width="342" alt="screen shot 2016-05-12 at 4 54 23 pm" src="https://cloud.githubusercontent.com/assets/11616747/15231681/36836394-1862-11e6-83ad-87f5953ada24.png">

Everywhere we have intl wired in has the text looking like this.

**Comment by yoni-tock** [comment]
Stoked about the changes! Highlights why we need to npm-shrinkwrap our dependencies though

**Comment by caridy** [comment]
@yoni-tock we rolled back the first attempt, folks from yahoo were expecting weird behaviors that we are fixing. Can you provide more details about that issue?

**Comment by shaosh** [comment]
@caridy So this 1.2.0 is still not available right now, right?

**Comment by caridy** [comment]
@shaosh correct, we are working on the release right now... once we close this, you should see it in NPM :)

**Comment by shaosh** [comment]
@caridy sounds good. Appreciate your effort in fixing the issue!

**Comment by caridy** [comment]
_update_: we are still seeing one issue when formatting pretty big numbers, e.g.: 

```
11.3.2_TRF -- FAILED Formatted value for 12344501000000000000000000000000000, af-u-nu-latn and options {"useGrouping":false,"minimumIntegerDigits":3,"minimumFractionDigits":1,"maximumFractionDigits":3} is 000,001; expected 12344501000000000000000000000000000,0.
```

we will postpone the release until tomorrow, latest code is in master, feel free to try it.

**Comment by yoni-tock** [comment]
@caridy we're probably having the same thing as Yahoo. We're using `react-intl` version 2.1.2 and react 0.15. The code that's rendering all funny in that screenshot is the following

```jsx
  render() {
    const displayMonthAs = this.props.displayMonthAs || 'numeric';
    const dateValue = this.props.dateValue;
    const dateMoment = _.isString(dateValue) ? time.fromDate(dateValue) : dateValue;
    const showWeekday = this.props.showWeekday ? { weekday: 'long' } : {};
    const showYear= this.props.showYear ? { year: 'numeric' } : {};
    return (
      <FormattedDate value={time.toJSDateObject(dateMoment)} {...showWeekday} {...showYear}
        day='numeric' month={displayMonthAs} locales={[this.context.locale]} />
    );
  }
```

**Comment by caridy** [comment]
@yoni-tock it is hard to tell from that code, can you be more specific? /cc @ericf

**Comment by yoni-tock** [comment]
@caridy Would it be more helpful for me to mock that with actual values? Or do you need the locale (I suspect it's `en-us`)? Most of the debugging I did was to binary search our artifacts and determine that what was published as `intl: 1.2.0` was leading to weird rendering.

I'm happy to dive in more to try to help! Just let me know what you need

**Comment by caridy** [comment]
@yoni-tock what I need is just the value of `locale`, `options` and `value` when rendering: `Intl.DateTimeFormat(locale, options).format(value)`

**Comment by yoni-tock** [comment]
Okay so looking into the `react-intl` source, it looks like [here](https://github.com/yahoo/react-intl/blob/master/src/format.js#L68) is where it's calling into that function. I'm still digging in to see exactly what's happening there and how are values are being passed down

**Comment by yoni-tock** [comment]
One example where we're getting bad behavior is:

`locale = "en-us"`
`options = {weekday: "long", year: "numeric", month: "numeric", day: "numeric"}`
`value  = (A Date object with string value Fri May 13 2016 00:00:00 GMT-0500 (CDT))`

**Comment by yoni-tock** [comment]
However I can't reproduce the behavior having cloned directly from commit 7b61f24f1ee8d4df119ef1382f025ac39c4dfd99 and trying to build from source.

**Comment by caridy** [comment]
solution for big numbers is in https://github.com/andyearnshaw/Intl.js/commit/226f0b0038a6d1198ea5b16f85939babcc999461

```
total 99 -- passed 99 -- failed 0
```

**Comment by caridy** [comment]
intl@1.2.1 is in NPM.

**Comment by caridy** [comment]
![image](https://cloud.githubusercontent.com/assets/38969/15258855/d7333d1e-191b-11e6-9d1c-41748ddb5155.png)

**Comment by yoni-tock** [comment]
Woo hoo!

**Comment by caridy** [comment]
Release notes: https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.1

**Comment by caridy** [comment]
v1.2.2 patch resolved some issues.
