### ISSUE TITLE
NumberFormat returns duplicated string.

### ISSUE THREAD

**Issue by Nodman** [andyearnshaw/Intl.js#176]
Hi everyone!

Getting result string  doubling when using NumberFormat 
 
    export const formatter = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'GBP',
        minimumFractionDigits: 2,
    });

using it like this:

    formatter.format(startPrice * period)

for example format(59.88) will produce '£59.88£59.88'
in FormatNumber src seem everything is fine, in debugger you can see:

![screenshot 2016-05-14 12 12 23](https://cloud.githubusercontent.com/assets/2991708/15267512/3a975050-19cd-11e6-9e7b-6f7c019d83df.png)
![screenshot 2016-05-14 12 12 08](https://cloud.githubusercontent.com/assets/2991708/15267516/4f6e5820-19cd-11e6-8ecc-bb5add3e6251.png)

for cycle is running 8 iterations except 4 causing doubling the result.
Maybe I'am missing something obvious...

**upd:** 
replacing for in loop with native for loop (just to test) resolved problem, but I still want to figure out what's wrong with for in part, would appreciate if someone help to understand this, thanks!

    for (var i = parts.length - 1; i >= 0; i--) {
         var part = parts[i];
         result += part['[[value]]'];
    }
    // for (var idx in parts) {
    //     var part = parts[idx];
    //     // a. Set result to a String value produced by concatenating result and part.[[value]].
    //     result += part['[[value]]'];
    // }

**Comment by arnekolja** [comment]
Same here when using Date.prototype.toLocaleTimeString and Date.prototype.toLocaleDateString

**Comment by watilde** [comment]
I just tried to reproduce this with the latest version as `Intl.js@v1.2.1` and on Chrome, but it seems worked correctly. My test code displayed `£59.88`.
+ Test page(see `console.log`): http://watilde.github.io/Intl.js-issues-176/index.html
+ Test code: https://github.com/watilde/Intl.js-issues-176/blob/gh-pages/index.html

Could I ask you the version of `Intl.js` and browser name you used?

**Comment by Nodman** [comment]
Thank you for response!

I am getting this issue with "intl": "^1.2.1" on Safari 9.1 
Never tested in Chrome because it's own Intl implemented, so no problem with Chrome and FF.

**Comment by lauterry** [comment]
Hello

I can also reproduce the issue with "intl": "^1.2.1" on Safari 9.1 

I've tested with "intl": "^1.1.0" on Safari 9.1 and the issue disappear.

**Comment by watilde** [comment]
You are right! I could reproduced this issue on Safari@9.1 and I think the reason why it happened is also correct. I could fix it by the change like you said, let me put it as a patch into a pull request.

**Comment by lauterry** [comment]
@watilde 👍

**Comment by Nodman** [comment]
@watilde Thank you! 
I think thread can be closed now.

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/pull/177
