### ISSUE TITLE
1.2.1 ugly Date format in Safari

### ISSUE THREAD

**Issue by Delagen** [andyearnshaw/Intl.js#178]
44:01 AM44:01 AM 66/66/20162016, 44:01 AM66/66/20162016, 44:01 AM
In angular 2. In 1.1.0 was missing leading zero
{{date|date:'shortTime'}}
{{date|date:'yMdjm'}}

angular/angular#3333

**Comment by eschiebel** [comment]
I am seeing the same issue.
`new Intl.DateTimeFormat('en', {month:'numeric', day: 'numeric'}).format(new Date()) `
returns "55/161655/1616" (today is 5/16)

similar issues with formatting times.

**Comment by caridy** [comment]
fixing this today.

**Comment by Delagen** [comment]
Again the same issue with missing leading zero on Safari
4:01 AM
6/6/2016, 4:01 AM
