### ISSUE TITLE
Intl not defined in Samsung Default Browser

### ISSUE THREAD

**Issue by MasDevProject** [andyearnshaw/Intl.js#180]
Hi guys,
thanks for your great work.

In all my browser Intl.js works just great but I noticed that using the Samsung default Browser I get an error "Intl not defined".

This is the complete error: http://i.stack.imgur.com/rx2dW.png

Thanks a lot

**Comment by caridy** [comment]
Dupe of https://github.com/andyearnshaw/Intl.js/issues/170
