### ISSUE TITLE
Trailing comma in arrays and object literals

### ISSUE THREAD

**Issue by triblondon** [andyearnshaw/Intl.js#181]
There are many examples of arrays with trailing commas on the last item.  Since the rules for where trailing commas are allowed in modern browsers can create unintuitive code (eg `['a', 'b', , ]` creates an array with *one* undefined element at the end) and it's a syntax error in IE8, should these be removed?

I notice that the polyfill claims to have some compatibility with IE8, but can't see how this can work with trailing commas on arrays and objects.

**Comment by caridy** [comment]
hmm, we probably lost some of that when transition to ES Standard Module syntax and transpilation with babel, I will investigate.
