### ISSUE TITLE
Browserify / Conditional Loading

### ISSUE THREAD

**Issue by SamAmiri** [andyearnshaw/Intl.js#185]
Hi Andy,

Thanks for the great polyfill, I am trying to conditionally load the polyfill in for Safari, but with the implementation that you provided `Browserify` does not support `require.ensure` that is only with Webpack. 

How should this be loaded?

**Comment by caridy** [comment]
@SamAmiri I'm not sure what else can you do with Browserify. But If you find out, let us know.

I normally suggest to avoid declaring an explicit dependency between a module and a polyfill, especially if you're using a bundler like browserify, and instead do your own thing to provision your runtime before evaluating your modules, or use the polyfill service from FT, which does that for you for free :)

**Comment by SamAmiri** [comment]
@caridy 

Thanks for the prompt response, I am basically thinking of going with just importing the package
