### ISSUE TITLE
datetime format bestfit does not process a single configuration

### ISSUE THREAD

**Issue by caridy** [andyearnshaw/Intl.js#190]
Because CLDR skeletons always contain more than one configuration, or a fixed configuration for single entries, we end up missing the opportunity to provide the best result in `BestFitFormatMatcher`.

```
> new intl.DateTimeFormat('es', {"month": "long"}).format(new Date("08/14/2016"))
'ago.' <-- should be agosto
```

More examples about these are here from @mkohlmyr:
* https://github.com/andyearnshaw/Intl.js/issues/179#issuecomment-222708076

/cc @juandopazo @watilde

**Comment by caridy** [comment]
The solution is to add some hard-wire in `BestFitFormatMatcher` to account for this cases.

**Comment by watilde** [comment]
Hmmm yeah it can be a hard code point like you said..

**Comment by juandopazo** [comment]
Yeah. I took a look at the code. The calendar data is there, it's just that the possible configurations that the polyfill generates don't include single options.

**Comment by caridy** [comment]
@juandopazo yes, we can included that as part of the data as well, that's the other part of the story.

**Comment by gabriel-miranda** [comment]
You can include the day and the month won't format either. Month can't use long for some reason. I'm trying to debug it.

**Comment by caridy** [comment]
@gabriel-miranda yes, this is for any format that should use a single element in the formatter.

**Comment by caridy** [comment]
solve by 20f322dcb47624cec6ba72addcef107c2de94e71

please, verify if this solves all your problems ;)

**Comment by gabriel-miranda** [comment]
@caridy Thanks for the tip I ended up parsing the relative date myself and using intl-relativeformat to support the languages. Maybe in the next months I will look up again for this. Ty anyway

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.5
