### ISSUE TITLE
Leading zeroes in Date format

### ISSUE THREAD

**Issue by Delagen** [andyearnshaw/Intl.js#191]
No leading zeroes for format string dd.MM.yyyy in safari in latest build.
#152

**Comment by caridy** [comment]
@Delagen can you provide more details? Maybe an example?

**Comment by Delagen** [comment]
Date 2016-06-07 output as 7.6.2016

**Comment by caridy** [comment]
@Delagen this is not a bug, the following is the output using polyfill and chrome (it is the same output):

```
new Intl.DateTimeFormat('en-GB', {
  day: 'numeric',
  month: 'numeric',
  year: 'numeric'
}).format(new Date(2016, 6, 7))
> "07/07/2016"

new Intl.DateTimeFormat('en', {
  day: 'numeric',
  month: 'numeric',
  year: 'numeric'
}).format(new Date(2016, 6, 7))
> "7/7/2016"
```

**Comment by Delagen** [comment]
Thanks. Does not know about such difference in locales
