### ISSUE TITLE
Proposal to .npmignore anything that's not needed for production

### ISSUE THREAD

**Issue by bensontrent** [andyearnshaw/Intl.js#199]
When using `npm install` with intl.js, I've found it requires 71 mb of disk space.  Can this be trimmed down for production?  I haven't researched the code yet, but it appears the `json` and `jsonp` folders are covered by complete.js?  Or if  `json` and `jsonp` are needed, is it possible to refactor duplicitous code? Could we lose the `src` and `lib` folders for npm installs? Could we direct npm to _just_ the `dist` folder?  I'd be happy to make a proposal through a pull request.

![image](https://cloud.githubusercontent.com/assets/5982592/16537802/9992152a-3fc2-11e6-8902-0ecb499ab5a2.png)

My sob story: I ran into a situation where I was using a corporate laptop that had a 128GB SSD hard drive; I had maybe 10 gb left at the beginning of the week, and then by Thursday the laptop crashed to the point a windows restore couldn't work as there wasn't space left.  I had been installing many projects using `npm install`, and I discovered that typically 80% of the space in node modules was taken up by the Intl.js package.  

For inspiration, I'm looking at [the connect package.](https://github.com/senchalabs/connect)  They obviously were saving every byte.
![image](https://cloud.githubusercontent.com/assets/5982592/16538218/2d0b2ba2-3fd2-11e6-94a6-513b350cc00e.png)

They use the "files" method in package.json to achieve this result when installing via npm.
![image](https://cloud.githubusercontent.com/assets/5982592/16538222/720674a0-3fd2-11e6-98e7-e2e4c5579a9b.png)

Their source remains untouched in github with test and other files not needed during production

![image](https://cloud.githubusercontent.com/assets/5982592/16538232/c3f97bd6-3fd2-11e6-8ae7-2edcd8a03408.png)

And considering the Intl.js's incredible popularity, economically, every byte counts. 
![image](https://cloud.githubusercontent.com/assets/5982592/16538238/3625a162-3fd3-11e6-8602-348f8ee1672b.png)
Those numbers are kind of amazing.

**Comment by andyearnshaw** [comment]
Those numbers _are_ amazing 😄.

Trimming down is tricky, as each of _Intl.complete.js_, _json_ and _jsonp_ offer an alternative option based on the polyfill consumer's preference. _Intl.complete.js_ is commonly only used in Node or packaged apps that run locally, whereas _json_ and _jsonp_ are lightweight alternatives for browser environments.

We could possibly ditch either _jsonp_ (~20M, whitespace/key quotes stripped) or _json_ (~56M, human readable), depending on which is more popular to serve.  @caridy, what do you think?

**Comment by caridy** [comment]
I will work on this on Thursday.

**Comment by caridy** [comment]
ok, finally I get a chance to look at this problem holistically, here are my thoughts:

* FT polyfill service relies on the npm pkg to build their own folder structure (they use `dist/` and `locale-data/jsonp`)
* People using browserify/webpack can choose individual locale data files (otherwise their bundle is unusable), and they do so from NPM :/, we can't really remove jsonp files from the pkg at this point.
* I suspect that others might use `locale-data/json`, and removing it from the pkg will require a version bump (but I think it is worth it, those account for more than a half of the pkg)
* I have revisited the docs, and the issues, and we've never talk about `locale-data/json/`, we might be fine.
* we can trimming everything else.

I will submit a PR soon.

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.5

**Comment by caridy** [comment]
@bensontrent I did some partial clean up, but unfortunately we can't really remove dist/ because people are using it directly. I plan to do so in 1.3.x, in the meantime, I will keep this open.

**Comment by bensontrent** [comment]
@caridy An 80% reduction in the npm package size? That's more than a modest partial cleanup, I'd say that's a win already. Here's what intl looks like after your revisions:

![image](https://cloud.githubusercontent.com/assets/5982592/18680503/c9f99c7a-7f18-11e6-86e0-342d4a428a78.png)

And here's a report by file type report:

![image](https://cloud.githubusercontent.com/assets/5982592/18680517/dd1f543e-7f18-11e6-926e-ab9b397e35e0.png)

Nice work!

**Comment by mgh** [comment]
Glad to see the file size going down!  But the `json` folder was removed in v1.2.5 -- for future reference, this should have probably been a major release, not a patch release, to avoid breaking the package for those of us that depended on it.

**Comment by caridy** [comment]
ok, with 1.2.6 we are going down to ~500K package (~5mb expanded), which I think is sufficient for now.

@bensontrent thanks a lot for pushing us to get to that point.

**Comment by bensontrent** [comment]
Holy cow @caridy I'm impressed - a 93% savings.  And look how popular Intl has become since we first started this conversation in July--the stats have doubled on what was already a very popular package.

My (certainly-inaccurate) napkin calculation estimates the 93% reduction in size saves 60 Terabytes of storage and transmission, every day. 

![image](https://cloud.githubusercontent.com/assets/5982592/20411379/17f22204-acd6-11e6-8ca2-38863b89f543.png)

Way to go! 😃
