### ISSUE TITLE
Intl polyfill not working on ipod device

### ISSUE THREAD

**Issue by nuruddeensalihu** [andyearnshaw/Intl.js#202]
Hi,

I adopted this great lib for my app and was working fine all devices . However, we noticed ipod devices are not able to start our app despite having the latest version of ios . We then discovered that our intl was not recognised. Below is the polyfill we use 

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,Promise,Array.from,Array.prototype.find,Array.prototype.includes,String.prototype.startsWith,String.prototype.includes,Math.sign,Intl.~locale.en,Intl.~locale.id,Intl.~locale.ru,Intl.~locale.fr&unknown=polyfill"></script>
`

We use react-intl for date, numbers as well as translations for italian, AR, EN, FR, ES, ID, RU, CH, CHZ , POLISH, PORT, VIET and DEUSCHE . THe polyfill above failed to load the intl for our device. When i changed to `npm install intl ` . It works fine. HOwever, we really want to go with the polyfill if possible. Please whats wrng with my polyfill above and how do i address it?.

**Comment by caridy** [comment]
What is the result of that url in that device? Most likely this will be a detection issue, in which case we will have to report the issue on the FT polyfill service repo.

**Comment by nuruddeensalihu** [comment]
@caridy it failed on startup of the app. running `window.location.pathname` returns something like `/android_asset/www/index.html` and the hash is `#/`. So basically the app didn't start up yet.

**Comment by caridy** [comment]
@nuruddeensalihu we need more information here... we need to know what the polyfill service is returning for that user-agent.

**Comment by nuruddeensalihu** [comment]
@caridy  it does not throw when registering. It does throw the error where the Intl is used. It throws unknown/defined on Intl services. It does not register for ipod devices.

**Comment by caridy** [comment]
@nuruddeensalihu sure, but there are two options, either the polyfill service is assuming that the browser you're using already have Intl, and therefore it sends nothing, or it sends the polyfill code but the polyfill, for some weird condition decides to know patch the runtime... and in order for us to help you, we need to know what the polyfill service is sending down.
