### ISSUE TITLE
ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in "/home/company/app/node_modules/intl/.babelrc" at 0, attempted to resolve relative to "/home/company/app/node_modules/intl"

### ISSUE THREAD

**Issue by iam-peekay** [andyearnshaw/Intl.js#204]
Hello. Lovely package so thank you for building it! 

I'm having one issue: the build keeps failing because of unknown plugin. I can't seem to figure out what's going wrong. Any help would be appreciated. 

Thank you.

**Comment by caridy** [comment]
Hmm, this is weird. Make sure you have installed it with npm. That package does exist, and it is declared in package.json, here is the npm link to it https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs.

Make sure you are running of master and a clean slate:

```bash
rm -rf node_modules
npm install
```

**Comment by iam-peekay** [comment]
@caridy thank you. I didn't have it installed -- thought that the one that is automatically installed via babel's es2015 preset would suffice, but i guess not. I fixed the problem by installing it with npm and including it in my `.babelrc`
