### ISSUE TITLE
Intl.DateTimeFormat doesn't format minutes and seconds properly

### ISSUE THREAD

**Issue by laskoviymishka** [andyearnshaw/Intl.js#219]
Related to angular/angular#10974
Seems like there is issue with Intl.DateTimeFormat.
When you try to format date with only minutes and/or seconds it ignore it and format as default.
It seems like there is only hour + minutes + seconds pattern support properly.
Here plnkr to describe issue: http://plnkr.co/edit/HdVrwbvZkcqZclwPJHaN?p=preview
Same as Microsoft/ChakraCore#1223
Reproducing in Safari.

**Comment by caridy** [comment]
This is a dupe of #190, and it was fixed few days ago, and will be part of the next release (on thrusday)!

**Comment by laskoviymishka** [comment]
Thx for update!

**Comment by laskoviymishka** [comment]
Closed via 20f322dcb47624cec6ba72addcef107c2de94e71
