### ISSUE TITLE
Dynamic Require Polyfill

### ISSUE THREAD

**Issue by iammerrick** [andyearnshaw/Intl.js#222]
Given the following polyfill extracted from the README, has anyone had success trying to accomplish this with dynamic requires for either, languages specific builds or multiple languages using the define plugin?

``` javascript
if (!global.Intl) {
    require.ensure([
        'intl',
        'intl/locale-data/jsonp/en.js'
    ], function (require) {
        require('intl');
        require('intl/locale-data/jsonp/en.js');
        runMyApp()
    });
} else {
    runMyApp()
}
```

For example...

let LOCALES = Global from DefinePlugin of a list of locales set by translators.

``` javascript
if (!global.Intl) {
    require.ensure([
        'intl',
        ...LOCALES
    ], function (require) {
        require('intl');
        LOCALES.forEach((locale) => require(locale));
        runMyApp()
    });
} else {
    runMyApp()
}
```

I think this can be accomplished by using Webpack's context feature, but that seems to be bring in _all_ locales. Any ideas for dynamic support of languages?

CC: @ericf

**Comment by mikesherov** [comment]
With Webpack, `System.import` is how you signify a dynamic require. Does that work?

**Comment by iammerrick** [comment]
Hey @mikesherov require.ensure is the webpack 1 version of System.import I am pretty sure :-)

**Comment by NekR** [comment]
Maybe have a pre-build step and insteal of using DrdinePlugin, make the JS file a template and pass to it requires data. Then dump all locales as `require("...")` and then build. You may even have plugin for that or loader :-)

**Comment by iammerrick** [comment]
@NekR would love that as a plugin, I thought that is exactly what DefinePlugin was supposed to do :-(

**Comment by NekR** [comment]
@iammerrick this is a surprise for me too. Probably DefinePlugin runs after `require` resolution is being done. Sad thing :-(

**Comment by iammerrick** [comment]
@NekR sad thing indeed :-(

**Comment by baseonmars** [comment]
It's possible to use the ContextReplacementPlugin to restrict which locales are loaded.

When you use webpack require with an expression instead of a string a context is created. A context in this case consists of a directory and a regular expression of the files to match. The default regular expression matches all files in the directory.

How you get the list of locales into your webpack config file will depend on your build setup.

```javascript
import ContextReplacementPlugin from 'webpack/lib/ContextReplacementPlugin';
const locales = ['de-DE', 'en-US', 'fr'];

...
plugins: [
new ContextReplacementPlugin(
                /intl[\/\\]locale-data[\/\\]jsonp$/,
                new RegExp(`^\.\/(${locales.join('|')})$`)
            )
]
```
