### ISSUE TITLE
NumberFormat dropping currency decimals in node

### ISSUE THREAD

**Issue by awolden** [andyearnshaw/Intl.js#223]
I think I have discovered a discrepancy in the Intl-polyfill and the standard implementation. In a browser (i.e. chrome), this is what I get:

```javascript
console.log(new Intl.NumberFormat('en-US', { currency: 'USD', style: 'currency'}).format(123))
"$123.00"
```

but, when am using the intl polyfill in node 4 this is what I get:

```javascript
require('intl');
console.log(new Intl.NumberFormat('en-US', { currency: 'USD', style: 'currency'}).format(123.00));
"$123"
```

TBH, I am not sure which one of these is the correct interpretation of the standard. Any help regarding this issue is appreciated.

Edit: I just tested the polyfill in safari and it behaves as I would expect and keeps the decimals. This issue seems to be isolated to Node.

**Comment by caridy** [comment]
v1.2.5 works just fine:

```
$ node -v
v6.3.1
$ node
> const poly = require('intl');
> console.log(new Intl.NumberFormat('en-US', { currency: 'USD', style: 'currency'}).format(123.00));
$123.00
> console.log(new poly.NumberFormat('en-US', { currency: 'USD', style: 'currency'}).format(123.00));
$123.00
```
