### ISSUE TITLE
latest version does not include local data

### ISSUE THREAD

**Issue by jonathanong** [andyearnshaw/Intl.js#227]
cause may be : https://github.com/andyearnshaw/Intl.js/issues/199 https://github.com/andyearnshaw/Intl.js/commit/9ad9a125ecf6ee695e23f8f976e98d3be3733aec

because they are not included, this instruction no longer works: https://github.com/andyearnshaw/Intl.js#intljs-and-browserifywebpack

not sure if the issue is that the instructions are outdated or if this change was accidental

**Comment by jonathanong** [comment]
oh i see. you are requiring the `js` file, whereas i'd prefer to just require the json.

**Comment by jonathanong** [comment]
let me know if this is a "will not fix"

**Comment by bensontrent** [comment]
Make sure you're referencing the `locale-data/jsonp/....` folder as found in the instructions rather than `locale-data/json` as the `json` folder was considered less dangerous to be removed as it was never officially documented.

**Comment by caridy** [comment]
yeah, if you really need the json files you will have to build them! I'm more curious about why do you need the json files. I will close this one, feel free to reopen if you have a strong reason :)

**Comment by 10xLaCroixDrinker** [comment]
@caridy keeping the JSON in the tar would allow a user to add locale data for a macro-language like no-NO using a combination of data for nn-NO and nb-NO
