### ISSUE TITLE
403 Forbidden due to invalid cert

### ISSUE THREAD

**Issue by OhCirca** [andyearnshaw/Intl.js#241]

**Comment by OhCirca** [comment]
![screen shot 2016-10-13 at 9 40 47 am](https://cloud.githubusercontent.com/assets/6751561/19351298/2ea1845e-9129-11e6-80b8-7749ed4fa28f.png)

**Comment by caridy** [comment]
For posterity, issues like this should be reported here: https://github.com/Financial-Times/polyfill-service/issues/new
