### ISSUE TITLE
maximumSignificantDigits: 0 throws error

### ISSUE THREAD

**Issue by indolering** [andyearnshaw/Intl.js#245]
The following error is triggered when using `maximumSignificantDigits: 0`: `Error: Value is not a number or outside accepted range`.

```
new Intl.NumberFormat('en-US', {maximumSignificantDigits: 0, currency: 'USD', style: 'currency', currencyDisplay: "symbol"});
```

This does not raise an error in Firefox nor Chrome.

**Comment by caridy** [comment]
We are following the specification:

https://tc39.github.io/ecma402/#sec-properties-of-intl-numberformat-instances

It clearly specify that this value should be a positive integer. I wonder what is the new safari doing, as well as edge, if they are all ignoring the error, then we should probably align with them and bring this to the committee for discussion.

**Comment by indolering** [comment]
Yeah, I just signed up for ESDiscuss : )

**Comment by caridy** [comment]
Closing this in favor of the discussion around spec definition.
