### ISSUE TITLE
2 digits month issue on Chrome Windows 10

### ISSUE THREAD

**Issue by lauterry** [andyearnshaw/Intl.js#248]
Hello

I'm trying to have a list of 2-digits month in a select component with the following code : 

```
var month2Digits = intl.formatDate(new Date(1970, +month - 1, 1), {month: '2-digit'})
```

Here is what i got : 

| month | month2Digits |  |
| --- | --- | --- |
| 1 | 01 |  |
| 2 | 02 |  |
| 3 | 03 |  |
| 4 | 03 | problem here |
| 5 | 04 |  |
| 6 | 05 |  |
| 7 | 06 |  |
| 8 | 07 |  |
| 9 | 08 |  |
| 10 | 09 | probleme here |
| 11 | 11 |  |
| 12 | 12 |  |

I have this issue on Chrome 54.0.2840.71 m (64 bits) Window 10 Professional

Best regards

**Comment by lauterry** [comment]
I have tried to put 2016 instead of 1970 and it works.

It seems to have a problem with 1970 on chrome window

**Comment by caridy** [comment]
@lauterry I'm not sure what the issue is, but if it is in Chrome, then you should create a bug against Chrome since it has built-in Intl implementation and this polyfill will simply opt-out.
