### ISSUE TITLE
question: how to include all locales in polyfill.io service?

### ISSUE THREAD

**Issue by thisguychris** [andyearnshaw/Intl.js#252]
Hi, 
What's the correct flag to use if I want to include all locales?

something like this?
`https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.all|always`

**Comment by caridy** [comment]
No, we don't offer that option, and we should never do IMO. Apps will normally run in one locale, or a subset of available locales. Those files are not small, and require pre-processing on the client. Loading all of them will kill the perf of your app. Feel free to re-open if you have a strong use-case.
