### ISSUE TITLE
locales with non normal whitespaces

### ISSUE THREAD

**Issue by kinslayeruy** [andyearnshaw/Intl.js#253]
formatting a percentage with locale "en-UY" will result in:

0.05 =>  "0,5 %"

The space between the 5 and the % is not a normal whitespace. I noticed that it happens on several other formats for this locale at least. Is there a reason for this inconsistency?

```
let options = {
        minimumFractionDigits: 1,
        maximumFractionDigits: 1,
        style: "percent"
 };
 let intFormat = new this._intl.NumberFormat("es-UY", options);
 
assert.equal(intFormat.(0.05), "0,5 %")       
``` 

the assert will fail since the spaces are different types of whitespaces

**Comment by caridy** [comment]
@kinslayeruy this is not really a problem, but a feature :), and matches implementations in browsers:

This is in chrome:

```js
> let options = {
        minimumFractionDigits: 1,
        maximumFractionDigits: 1,
        style: "percent"
 };
> new Intl.NumberFormat("es-UY", options).format(0.05).charCodeAt(3)
160
```

The character 160 is the non-breaking space, which is used in places where you don't want a breakline to be used, otherwise the meaning of the formatted value might be lost.
