### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by Turbo87** [andyearnshaw/Intl.js#257]
I'm using this Intl polyfill through https://polyfill.io/v2/docs/ and four days ago I started seeing `Invalid regular expression` errors for some of my users. It's happening in multiple different browsers, with Chrome Mobile 44 on a Samsung device giving the most descriptive error message: 

```
Invalid regular expression: /[\s\S]{6}(((((((())))))))[\s\S]{1})/: Unmatched ')'
```

I'm not sure if this error is indeed coming from inside the polyfill or if something else is broken, but it seems quite likely given that the latest release of this polyfill is also 4 days old and nothing else in my application code changed in the last week.

**Comment by caridy** [comment]
@mtlewis could this be related to #244?

**Comment by Turbo87** [comment]
closing this in favor of https://github.com/andyearnshaw/Intl.js/issues/256
