### ISSUE TITLE
 Can't find @types modules((Typescript .d.ts files)) for intl

### ISSUE THREAD

**Issue by youthcity** [andyearnshaw/Intl.js#258]
Hello, Can you add a type declaration file in NPM?such as, @types/intl

**Comment by caridy** [comment]
This is a polyfill for an ECMA 402 Standard. I suspect that TS and Flow already have the type annotations for all ECMA Intrinsics, and Intl is one of them, [more info here](https://tc39.github.io/ecma402/#sec-402-well-known-intrinsic-objects).

**Comment by youthcity** [comment]
Thank you. 
I find a solution to use Intl.js in the typescript. Just require('intl'),It works.
