### ISSUE TITLE
Safari + Polyfill : Not found https://cdn.polyfill.io/v2/Intl.min.js.map 

### ISSUE THREAD

**Issue by Selsynn** [andyearnshaw/Intl.js#263]
Hello
Using https://github.com/andyearnshaw/Intl.js#intljs-and-ft-polyfill-service i ended with a 
`Failed to load resource: the server responded with a status of 404 (Not Found) `
for https://cdn.polyfill.io/v2/Intl.min.js.map 
(and effectively, i can't access to https://cdn.polyfill.io/v2/Intl.min.js in my browser)

code snippet
`    
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.fr"></script>
`
And it's before my require of Intl in my app script

I used the yahoo/react-intl, but they direct on explication on polyfill here, so I post the issue here.

I'm totally at loss what is wrong.

Sorry for my kitchen english, it's not my native language

**Comment by Selsynn** [comment]
I restarted the mac and installed new updates (Safari 10).

I don't have problems now with loading, but files found are empty 
When I delete min from url i get this file 
```
/* Polyfill service v3.16.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: safari/10.0.0
 * Features requested: Intl.~locale.en
 *  */

/* No polyfills found for current settings */
```

**Comment by caridy** [comment]
Safari 10 has Intl implemented natively, the polyfill service detects that, and it sends an empty payload, that's the expected behavior. If you have issues with the polyfill service, not with the polyfill itself, you can open an issue here https://github.com/Financial-Times/polyfill-service/issues/new
