### ISSUE TITLE
No locale data has been provided for this object yet

### ISSUE THREAD

**Issue by eminoda** [andyearnshaw/Intl.js#271]
when i use Angular4.0, my browser show this error:No locale data has been provided for this object yet.

i open this comment,but no use
````
/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.
````

**Comment by caridy** [comment]
You need to import the corresponding locale data, e.g.:

```js
import 'intl';
import 'intl/locale-data/jsonp/en.js';
```

assuming that `en` is the locale that you want/need. More details here: https://github.com/andyearnshaw/Intl.js#intljs-and-browserifywebpack
