### ISSUE TITLE
Intl.NumberFormat inaccurate return after 17 digits

### ISSUE THREAD

**Issue by j-clarkson** [andyearnshaw/Intl.js#272]
When there are more than 17 digits in a number (regardless of decimal places), the digits at and after the 17th place in the return value seem to be inaccurate. The inaccurate return value also changes between Intl.js versions.

Example:
`new Intl.NumberFormat('en-us', {style: 'decimal', maximumFractionDigits: 5, minimumFractionDigits: 0}).format(1234567891234.123456789)`

In version 1.0.1:
returns 1,234,567,891,234.12354

In version 1.2.5:
returns 1,234,567,891,234.12352

Expected result:
1,234,567,891,234.12346

Is there a limit to the number of characters supported or would this be a bug?

**Comment by Huulivoide** [comment]
That is a JavaScript limitation. JavaScript stores all numbers in IEEE 754 format, thus limiting the precision to 17 decimal places.

**Comment by j-clarkson** [comment]
> That is a JavaScript limitation. JavaScript stores all numbers in IEEE 754 format, thus limiting the precision to 17 decimal places.

Helpfully pointed out by a contributor.
