### ISSUE TITLE
TypeError: weekdayFormatter.format is not a function

### ISSUE THREAD

**Issue by yarossia** [andyearnshaw/Intl.js#284]
Using TypeScript 2.3.1 with material-ui 0.17.2. Trying to integrate polyfill for material's ui DatePicker component and it gives me this error: **TypeError: weekdayFormatter.format is not a function.** 

```javascript
import * as areIntlLocalesSupported from "intl-locales-supported";

private dateTimeFormat: any;
constructor(public props) {
    super(props);
    if (areIntlLocalesSupported(["nl-NL"])) {
      this.dateTimeFormat = global.Intl.DateTimeFormat;
    } else {
      const IntlPolyfill = require("intl");
      this.dateTimeFormat = IntlPolyfill.DateTimeFormat;
      require("intl/locale-data/jsonp/nl-NL");
    }}
```

and the DatePicker component

```tsx
<DatePicker
        DateTimeFormat={(() => this.dateTimeFormat) as any}
        formatDate={this.format}
        locale="nl-NL"
        floatingLabelText={this.props.label}
        className="form-element full-size"
        value={Time.maybe(this.state.value)}
        onChange={this.onChange}
        errorText={this.state.errorText || this.props.error || ""}
/>
```

**Comment by caridy** [comment]
This doesn't seem to be related to this project. In your code, `(() => this.dateTimeFormat)` where `this` reference to the react component I presume. Feel free to reopen if you have a better repro case that does not use react.

**Comment by yarossia** [comment]
I think, this pointing to variable dateTimeFormat which is taking value depending on if block using your library.

**Comment by caridy** [comment]
No, that will be the React component implementation of DatePicker I presume. There is no `dateTimeFormat` member property lookup in this polyfill that I know of.
