### ISSUE TITLE
Currency specific patterns

### ISSUE THREAD

**Issue by emattias** [andyearnshaw/Intl.js#286]
I was a able to add support for SEK currency with the `en` locale by taking [the en locale](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/en.json) and adding `SEK: 'kr'` to the currencies object and then doing:
```javascript
IntlPolyfill.__addLocaleData(en)

Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat
Intl.NumberFormat = IntlPolyfill.NumberFormat
```

That worked (if you have suggestions on a better way to do it I'm up for suggestions :) ), but then this 
```javascript
new Intl.NumberFormat('en', { style: 'currency', currency: 'SEK' }).format(1)
``` 
results in `kr1` when it should be `1kr` for SEK currency. I still want `USD` currency to be `$1`

I have found that the order is controlled by [positivePattern](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/en.json#L274) but it is global for all the currency outputs for that locale. 

How can I make SEK have the pattern `{number}{currency}` and USD `{currency}{number}` for the same locale?

**Comment by caridy** [comment]
This is mostly CLDR, which doesn't have that info today from what I can tell. Also, we are producing the same result produced by Chrome, Safari, and FF:

```
new Intl.NumberFormat('en', { style: 'currency', currency: 'SEK' }).format(1)
"SEK1.00"
```

**Comment by emattias** [comment]
Hmm, so is there an issue tracker for CLDR? None of the [cldr repos](https://github.com/unicode-cldr) seem to have issues enabled 🤔

**Comment by caridy** [comment]
unicode.org/cldr/trac/newticket

**Comment by emattias** [comment]
Thanks!
