### ISSUE TITLE
Undefined timezone

### ISSUE THREAD

**Issue by mir3z** [andyearnshaw/Intl.js#293]
`Intl.DateTimeFormat().resolvedOptions().timeZone` returns `undefined` when using the Intl.js and `CET` when using native browser API.

**Comment by martindederer** [comment]
I stumbled upon the lack of the timezone information in the output of Intl.DateTimeFormat. Maybe [this](https://github.com/andyearnshaw/Intl.js/blob/e93b11494394f6dc02d7831af5d6930e63af3bb3/src/12.datetimeformat.js#L1021) is somehow related.

**Comment by caridy** [comment]
not supported today: https://github.com/andyearnshaw/Intl.js#not-implemented

duped of #19
