### ISSUE TITLE
Intl.Collator Compare is dead slow in IE

### ISSUE THREAD

**Issue by SathishKannan** [andyearnshaw/Intl.js#321]
Below is my sample code, I have more than 7k records in my table, below code executes when I click on table header to sort columns,

var collator = new Intl.Collator(undefined, {
  numeric: true,
  sensitivity: 'base'
});
var objs = [{name: '1_Document', size: 40}, {name: '11_Document', size: 50}, {name: '2_Document', size: 60}];

objs.sort(function(a, b) { return collator.compare(a.name, b.name) })

But it is dead slow in IE and "Stop Script" message pops-up. Can someone please help?

**Comment by okuryu** [comment]
Intl.js doesn’t provides `Intl.Collator`.
https://github.com/andyearnshaw/Intl.js/blob/master/README.md#what-about-intlcollator
