### ISSUE TITLE
R: This project is no longer under active maintenance

### ISSUE THREAD

**Issue by emilyrohrbough** [andyearnshaw/Intl.js#344]
@andyearnshaw, @caridy, @ericf and @kate2753,

Thank you for the work and effort you've put into creating this Polyfill! ❤️ 

My team uses this polyfill heavily to support localization in IE 10 browsers and embedded apps. I understand the project in is no longer maintained as outlined on https://github.com/andyearnshaw/Intl.js/issues/341. Reading through the posting it was mentioned:

> As ECMA-402 support has grown in browsers over the past few years (even IE11 has basic support), there are better polyfills for specific features and enhancements.

Would you mind sharing the polyfills you feel are better? Specifically around `Intl.DateTimeFormat` and `Intl.NumberFormat`? Thank you!

**Comment by okuryu** [comment]
Try FormatJS.
https://formatjs.io/

**Comment by caridy** [comment]
A lot of good info and links in this page: https://momentjs.com/docs/#/-project-status/recommendations/

**Comment by emilyrohrbough** [comment]
Great! Thank you @okuryu  & @caridy
