### ISSUE TITLE
Should we build Intl.js with packed-in locale data for each language?

### ISSUE THREAD

**Issue by andyearnshaw** [andyearnshaw/Intl.js#37]
`Intl.complete.js` is too bloated to serve to clients, which are unlikely to need data for any locale other than the one defined by their language setting.  On the flip side, providing `Intl.min.js` _without_ locale data introduces the following complications:

 - Intl.js requires a special case where the developer needs to check for lack of native `Intl` and then add the required data either in a blocking manner or asynchronously, adding extra hurdles not necessary with native Intl.
 - The client code needs to ensure data is available on the server for the specific locale and provide a fall back to the language otherwise.  This could result in multiple requests to the server or writing complex server-side code to handle fallbacks.  Likewise, the client may need to canonicalise tags in some cases.

__A potential solution__ to this problem is to write a build script that will compile each language―and the language's sub tag―data into `Intl.min.js`, resulting in, for example, `Intl.aa.min.js`, `Intl.af.min.js`, `...`, `Intl.en.min.js`.  The developer could write the necessary server- or client-side code, either based on the `Accept-Language` header or `navigator.language || navigator.userLanguage`, to choose the base `Intl.<language>.min.js` file accordingly.

One potential issue is with deprecated or mapped language tags.  I'm not sure how likely these are to appear in legacy, modern or future browsers.

**Comment by caridy** [comment]
As part of the CLDR json refactor that is now in 1.0.0x, I did some work around this, trying to match what we are doing with intl-messageformat, but I found some undesired side effects:

* some top level locales will have a lot of data (en, es, etc)
* since data formats are expanded when locale data is added to Intl, it implies initializing all locales in a bundle even though you probably need only one (this could be solved by doing it lazily when needed)
* optimizations are gaining us almost nothing, and it is very complex to produce.

**Comment by caridy** [comment]
Ok, I finally get a chance to revamp the package structure, the new structure is composed of:

```
$ tree src/
src/
├── 10.collator.js
├── 11.numberformat.js
├── 12.datetimeformat.js
├── 13.locale-sensitive-functions.js
├── 5.conventions.js
├── 6.locales-currencies-tz.js
├── 7.requirements.js
├── 8.intl.js
├── 9.negotiation.js
├── cldr.js
├── core.js
├── exp.js
├── main.js
└── util.js
```

which is very granular and matches the section number from the spec.

this is the first step to upgrade the package to match 3rd edition + all new features.
