### ISSUE TITLE
Update readme to show how to switch between Intl vs IntlPolyfill

### ISSUE THREAD

**Issue by lwelti** [andyearnshaw/Intl.js#41]
is it possible to show an example of how to detect if Intl is available then use IntPolyfill in nodejs and Browser.
thanks!

**Comment by caridy** [comment]
it was already documented in readme.

**Comment by GlebDolzhikov** [comment]
Sorry for dumb question, but i can still understand do i need to include Intl.js or https://cdn.polyfill.io/v2/polyfill.min.js it will be enough? I asked about browser implementation

**Comment by caridy** [comment]
Yes, you have to include `https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en`, or the corresponding locale that your app requires. Otherwise your app will not work on safari and other old browsers.

**Comment by GlebDolzhikov** [comment]
But https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en isn't update my ancient ES methods like Date.prototype.toLocaleString() so this locales data stay unusable.

**Comment by caridy** [comment]
Not true. If the polyfill is applied (it Intl is not implemented by the browser), then it calls `IntlPolyfill.__applyLocaleSensitivePrototypes()`, which, by spec, replaces the number and data `toLocaleString()` functions with the localized version of them.

**Comment by GlebDolzhikov** [comment]
Any way this way isn't work in my environment (on TV) i try to test it in old opera and i get an error like 
Object.defineProperty: first argument not an Object

I use moment JS but it's my example anyway:

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>
<script>
    var date = new Date();
    var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };

    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById(el).innerHTML = date.toLocaleDateString('de-DE', options) ;
    });
</script>
<div id="el"></div>
`

**Comment by caridy** [comment]
Hmm, what version of opera? In theory, the polyfill works in ES3-compatible browsers, but we could have introduced a bug or something in recent versions.
