### ISSUE TITLE
Investigate workarounds for failing tests in Chrome

### ISSUE THREAD

**Issue by andyearnshaw** [andyearnshaw/Intl.js#54]
Chrome is currently failing tests where properties of `Array.prototype` and `Object.prototype` are tainted.  Unlike #53, which affects the test environment, the actual test is failing with the message:

> "{ browserName: 'chrome', version: '31', platform: 'OS X 10.9' }": "unknown error: Client code can adversely affect behavior: setter for 1.",

This issue is specific to Chrome and does not affect v8/Node.js.

**Comment by andyearnshaw** [comment]
Looks like this is back to not failing again.  I'll close it for now and we can wait to see if it springs up again.

**Comment by caridy** [comment]
@andyearnshaw as part of the refactor, I'm now picking up the tests from 262 differently, but the outcome should be pretty much the same.
