### ISSUE TITLE
Currency formatting with currencyDisplay="name"

### ISSUE THREAD

**Issue by hakanson** [andyearnshaw/Intl.js#57]
In Chrome, when I format a currency by name, I get

```
(12345.67).toLocaleString("en-US", { style : "currency", useGrouping: true, currency : "USD", currencyDisplay: "name"})
"12,345.67 US dollars"
```

Using `Intl.js` I get `undefined` in the output

```
(12345.67).toLocaleString("en-US", { style : "currency", useGrouping: true, currency : "USD", currencyDisplay: "name"}) 
"undefined12,345.67" 
```

Internet Explorer 11 treats "name" the same as "code" showing `USD 12,345.67`

Also, a similar bug exists in Firefox.
[Bug 866372 - Currency formatting with currencyDisplay="name" results in error](https://bugzilla.mozilla.org/show_bug.cgi?id=866372)

**Comment by jcrben** [comment]
I was trying to use this but using code instead of name is a problem...
