### ISSUE TITLE
toLocaleString not respecting short format (numeric, numeric, numeric)

### ISSUE THREAD

**Issue by bthecorgi** [andyearnshaw/Intl.js#64]
(new Date(1)).toLocaleString('en-US', { year: 'numeric', month : 'numeric', day : 'numeric' });

"31 Dec 1969"  instead of "12/31/1969"

**Comment by JonyGreen3** [comment]
you can try this free <a href="http://www.online-code.net/format-html-js-css.html">online js beautifier</a> to format the javsscript code.
