### ISSUE TITLE
Breaking down the Intl.js source code

### ISSUE THREAD

**Issue by andyearnshaw** [andyearnshaw/Intl.js#67]
I've been experimenting making the source code a little more modular to try and achieve the following results:

 - Better organisation of source code
 - Easier to extend with missing or newer spec features and proposals
 - No need to rebuild Intl.complete.js every time we need to run the tests
 - Configurable build process (e.g. build without DateTimeFormat)

I figured this was necessary when I started looking at the timezone stuff, so I've been doing bits here and there when I could.  The [__modularsrc__](https://github.com/andyearnshaw/Intl.js/tree/modularsrc) branch is my most recent effort, with the polyfill being fully functional in Node.js but with no current build process.  I've probably made it a little more complicated than I originally hoped for, because of how Node's modules work.  There are some "circular" requires (e.g. `src/intl.js` requires `src/locale.js` which requires `src/intl.js` to get the Intl object) but I think I can eliminate those.

I was looking into using UglifyJS2's AST tree transformer to build all the files together with optional minification and source maps.  Browserify doesn't seem to be appropriate and adds a bit of cruft (including a `require()` shim).

I'd like to hear some thoughts and feelings on this before proceeding, because it's quite a large change and I may not have taken the best approach so far.

/cc @caridy, @ericf, @drewfish

**Comment by caridy** [comment]
This is done, merged into master, and will get consolidated into 1.0.0-rc-1 in PR https://github.com/andyearnshaw/Intl.js/pull/85
