### ISSUE TITLE
Intl.DateTimeFormat returns month:long instead of month:short

### ISSUE THREAD

**Issue by fhemberger** [andyearnshaw/Intl.js#68]
```js
global.Intl = require('intl');
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var options = {year: "numeric", month: "short", day: "numeric"};
console.log(new Intl.DateTimeFormat("en", options).format(date));
```

Expected: `Dec 20, 2012`
Actual: `December 20, 2012`

**Comment by bakura10** [comment]
ping @jasonmit

Could we have someone at Yahoo to fix this very long-awaited bug? I've tried to dig into the code myself but definitely too obscure for me. I know this must be a complex piece of software, but having date not correctly showing on Safari and iOS since nearly one year is quite annoying, actually :(.

Thanks in advance! :)

**Comment by caridy** [comment]
ok, we will try to get someone to fix this.

**Comment by bakura10** [comment]
Thanks! ;)

**Comment by okuryu** [comment]
I'll try to take a look if no one else wants to do. :)

**Comment by andyearnshaw** [comment]
@okuryu that would be an enormous help.  The reason I haven't gotten round to it is that I don't have much time for personal projects and this is not a simple change.  As per #77, we need to remove the data pre-compiling step and move some of the logic from the data compiler to the main formatting code.

Side note: this isn't strictly a bug, Intl.js actually supports the minimum subsets of date formats required by the specification.

**Comment by ericf** [comment]
> Side note: this isn't strictly a bug, Intl.js actually supports the minimum subsets of date formats required by the specification.

We can also file a bug against the spec to see if it's possible for it to add more specification around the output of the formatters — although it's likely to be a big can a worms.

**Comment by andyearnshaw** [comment]
I think those subsets were chosen as some locales will be missing some
formats. It's not even required (but it is recommended) that
implementations use CLDR, so there's always a chance of different outputs
in different environments. Norbert could probably tell you the exact
reasons.

Side note: this isn't strictly a bug, Intl.js actually supports the minimum
subsets of date formats required by the specification.

We can also file a bug against the spec to see if it's possible for it to
add more specification around the output of the formatters — although it's
likely to be a big can a worms.

—
Reply to this email directly or view it on GitHub
<https://github.com/andyearnshaw/Intl.js/issues/68#issuecomment-74693089>.

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/pull/85

**Comment by fhemberger** [comment]
Great, thank you!

**Comment by caridy** [comment]
1.0.0-rc-1 is in npm, help us to test it...

**Comment by fhemberger** [comment]
@caridy Both of my previous test cases work fine with 1.0.0-rc-1. :+1:
