### ISSUE TITLE
Intl.DateTimeFormat with just one option

### ISSUE THREAD

**Issue by juandopazo** [andyearnshaw/Intl.js#75]
`Intl.DateTimeFormat` seems to work fine if you use all its options. For example, the behavior of the polyfill for this looks correct:

```js
alert(new Intl.DateTimeFormat("en-US", {weekday: "long", year: "numeric", month: "long", day: "numeric"}).format(Date.now())); // Tuesday, September 23, 2014
```

However, when you specify only one option, the polyfill seems to include other parts of the date:

```js
// Chrome
new Intl.DateTimeFormat("en-US", {weekday: "long"}).format(Date.now()); // Tuesday
// IE
new Intl.DateTimeFormat("en-US", {weekday: "long"}).format(Date.now()); // Tuesday
// Polyfill
new IntlPolyfill.DateTimeFormat("en-US", {weekday: "long"}).format(Date.now()); // Tuesday, September 23, 2014
```

/cc @caridy @ericf

**Comment by mjackson** [comment]
I just ran into this issue as well and thought I was going crazy.

```js
// Chrome
new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date) // "Feb"
// Polyfill
new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date) // "February 2015"
```

@andyearnshaw Can you shed any light here?

**Comment by caridy** [comment]
related to https://github.com/andyearnshaw/Intl.js/issues/68, we will try to fix it asap.

**Comment by mjackson** [comment]
@caridy Thank you! :heart:

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/pull/85

**Comment by ronjouch** [comment]
@caridy thanks too for this fix! Fantastic work :)

**Comment by caridy** [comment]
1.0.0-rc-1 is in NPM, help us to test it...

**Comment by mesrob-axs** [comment]
Following issue on Safari. 
`Intl.DateTimeFormat('en', {month: 'long'}).format(new Date()); //"Jul"`

**Comment by caridy** [comment]
@mesrob-axs yes, https://github.com/andyearnshaw/Intl.js/issues/125 and https://github.com/andyearnshaw/Intl.js/issues/126
