### ISSUE TITLE
non-Latin percentages doesn't bear the correct percent sign

### ISSUE THREAD

**Issue by eddydas** [andyearnshaw/Intl.js#78]
In ar-sa, nu=arab
But the formatted percentage sign is always the Latin percent sign instead of the Arabic one.

The fix should be in function FormatNumber (numberFormat, x)
where you need something like this at the end of the function:

if (internal['[[style]]'] === 'percent') {
        result = result.replace('%', ild.percent);
    }

**Comment by caridy** [comment]
I think this is solved now with the new cldr data.
1.0.0-rc-1 is in NPM, help us to test it...
