### ISSUE TITLE
"2-digit" date formatting is different from native implementation

### ISSUE THREAD

**Issue by ragulka** [andyearnshaw/Intl.js#79]
```javascript
var date = new Date(2014, 3, 12),
      options = { day: '2-digit', month: '2-digit', year: 'numeric' };

console.log( date.toLocaleDateString('et', options) );
console.log( date.toLocaleDateString('en', options) );

// Native output
"12.04.2014"
"04/12/2014"

// Intl.js output
"12.4.2014"
"4/12/2014"
```

As you can see, Intl.js fails to pad the month number with a zero (`4` vs `04`).

**Comment by caridy** [comment]
related to https://github.com/andyearnshaw/Intl.js/issues/68

**Comment by caridy** [comment]
1.0.0-rc-1 is in NPM, help us to test it...

**Comment by efkan** [comment]
I use version 1.0.0 .
if I modify the native Date object and get an output using `console.log()` like the following I encounter the same issue;

    Date.prototype.toLocaleDateString = require('intl').__localeSensitiveProtos.Date.toLocaleDateString;
    
    var  d=new Date()
    console.log(d.toLocaleDateString('tr'))

    // Expected output
    "03.08.2015"

    // Console output
    "3.08.2015"
