### ISSUE TITLE
error when loading into Rhino 

### ISSUE THREAD

**Issue by hqm** [andyearnshaw/Intl.js#81]
Hi,

I'm trying to load Intl.js into Rhino, the js interpreter that is written in Java. I tried using both Rhino 1.7R3 and 1.7R4 (the latest) and I get the following error when loading the library:

PRODUCTION $ java -jar /Users/hminsky/src/rhino.jar -O -1
java -jar /Users/hminsky/src/rhino.jar -O -1
Rhino 1.7 release 3 2011 07 19
js> load("/Users/hminsky/src/intl.js/Intl.js/dist/Intl.js")
load("/Users/hminsky/src/intl.js/Intl.js/dist/Intl.js")
js: "/Users/hminsky/src/intl.js/Intl.js/dist/Intl.js", line 1357: uncaught JavaScript runtime exception: TypeError: Expected argument of type object, but instead had type undefined
	at /Users/hminsky/src/intl.js/Intl.js/dist/Intl.js:1357
	at /Users/hminsky/src/intl.js/Intl.js/dist/Intl.js:1
	at <stdin>:2

That line is

    /* 11.3.2 */$$core$$defineProperty($$core$$Intl.NumberFormat.prototype, 'format', {
        configurable: true,
        get: $$core$$GetFormatNumber
    });

For some reason the .prototype value seems to be undefined

Have you seen this issue before? Is there some workaround for Rhino ?

Thank you

hminsky@nestlabs.com

**Comment by hqm** [comment]
A workaround is to force this function to return false


    var $$core$$Intl = {},

        $$core$$realDefineProp = (function () {
//            try { return !!Object.defineProperty({}, 'a', {}); }
//            catch (e) { return false; }
         return false;
        })(),


This make most of the regression tests pass, with the exception of those that try to check if the Intl object is read-only.

I guess Rhino's defineProperty functionality does not meet the current ECMAscript guidelines?

**Comment by hqm** [comment]
I reported a Rhino bug with defineproperty, as https://bugzilla.mozilla.org/show_bug.cgi?id=1123640

**Comment by caridy** [comment]
probably fixed by https://github.com/andyearnshaw/Intl.js/pull/94
1.0.0-rc-1 is in NPM, help us to test it...
