### ISSUE TITLE
New release with FF bugfix

### ISSUE THREAD

**Issue by jerrymf** [andyearnshaw/Intl.js#82]
Hello,

could you make new release with your FF bugfix included? I would like to use it, but the latest release downloaded by npm crashes in FF due to RegExp.lastMatch is undefined.

Thx very much.

**Comment by andyearnshaw** [comment]
Sorry, I get barely any time for personal projects these days.  I'll try and issue new release over the next few days.

**Comment by caridy** [comment]
@andyearnshaw we could take care of that if needed.

**Comment by andyearnshaw** [comment]
@caridy: that would be fantastic.  I've given both you and @ericf push access, let me know if you need to extend this to anyone else.

**Comment by caridy** [comment]
awesome, we will take care of this one.

**Comment by caridy** [comment]
I will probably release 1.0.0-rc-1 or something along those lines since this includes the whole refactor and so.

**Comment by tume** [comment]
Any updates on this? Also having the same issue.

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js/pull/85

**Comment by caridy** [comment]
1.0.0-rc-1 is in NPM, it should have fixed this issue, help us to test it...
