### ISSUE TITLE
I would like to have a rails gem install option

### ISSUE THREAD

**Issue by acdesouza** [andyearnshaw/Intl.js#87]
I'm using this in a Rails App. And, because of Rails Asset Pipeline I would prefere use it as a gem.

So, I created this project: https://github.com/acdesouza/intljs-rails

If you prefer to maintain it, I can delete the project.

**Comment by daemonsy** [comment]
If you gemified the project just for bundling it, consider using `https://rails-assets.org/`

Add it as a gem source, and you can require bower assets. 

```ruby
source 'https://rails-assets.org' do 
  gem 'rails-assets-intl', '0.1.4'
end
```

It even helps you match up to bower versions. 

```javascript

// application.js
//= require intl
```

This `require` line exposes the `main` key in bower.json, which in this project, is exactly what you want. 

https://github.com/andyearnshaw/Intl.js/blob/master/bower.json#L5

Hope that helps.

**Comment by caridy** [comment]
same as in https://github.com/andyearnshaw/Intl.js/issues/97#issuecomment-110072445
