### ISSUE TITLE
The polyfill doesn't work in IE8

### ISSUE THREAD

**Issue by ikr** [andyearnshaw/Intl.js#96]
Opening this in IE8 on Windows XP SP3

```html
<html>
  <head>
    <script src="https://rawgit.com/andyearnshaw/Intl.js/master/dist/Intl.min.js"></script>
    <script src="https://rawgit.com/andyearnshaw/Intl.js/master/locale-data/jsonp/en.js"></script>
    <script src="https://rawgit.com/andyearnshaw/Intl.js/master/locale-data/jsonp/de.js"></script>
  </head>

  <body>
    <script>alert(window.Intl);</script>
  </body>
</html>
```

Results in `undefined` alerted. In IE9 the same code alerts `[object Object]`

Demo: https://demo.trade.stc.ch/Intl.html (mind the self-signed cert)

**Comment by ikr** [comment]
Sorry. The invalid cert is the problem. IE8 on XP refuses to load anything into a Web site with an invalid SSL cert.

**Comment by andyearnshaw** [comment]
Thanks for the followup, I wasn't sure when I'd have time to look into this.
