### ISSUE TITLE
Support for month,day,hour,minute and year,month,day,hour,minute formats

### ISSUE THREAD

**Issue by endragor** [andyearnshaw/Intl.js#98]
I know they are non-must, according to the spec, but we use them in production, and would love to see the polyfill support them.
I don't think a format like `May 20, 12:26 PM` is uncommon. We use the version with the year when the year is not current.
If you provide one of these formats to `Intl.DateTimeFormat` right now, you'll get the longest possible format: `Wednesday, May 20, 2015, 12:26:40 PM`.

**Comment by Spy-Seth** [comment]
I'm having the same issue I want to use short weekday format but in polyfilled environment its do not work.


```javascript
require('./intl-polyfill');

var dateTimeFormatFr = new Intl.DateTimeFormat('fr-fr', {weekday:'short', year:'2-digit'});
console.log(dateTimeFormatFr.format(Date.now()));
// Result: "vendredi 5 juin 2015"
// Expected: "ven. 5 juin 15"

var dateTimeFormatEn = new Intl.DateTimeFormat('en-uk', {weekday:'short', year:'2-digit'});
console.log(dateTimeFormatEn.format(Date.now()));
// Result: "Friday, June 5, 2015"
// Expected: (I do not know exactly, but not the actual result)
```

**Comment by endragor** [comment]
@Spy-Seth The format you need is actually `{weekday: 'short', year: '2-digit', month: 'long', day: 'numeric'}`. That set of fields must be supported, according to the spec.
Your issue is that the polyfill does not support `2-digit` format for `year` and `short` format for `weekday`. I believe you should file a separate ticket.

**Comment by caridy** [comment]
duplicated of https://github.com/andyearnshaw/Intl.js/pull/85, should work properly in 1.0.0-rc-1

**Comment by endragor** [comment]
Confirmed works as expected in 1.0.0-rc-1. Thank you!
