### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by lexdon** [andyearnshaw/Intl.js#99]
The package for Intl.js on npm was last updated [a year ago](https://www.npmjs.com/package/intl). Could we pretty please get an update published?

**Comment by gpbl** [comment]
I'm a bit worried for the future of this project, since it is needed to use Intl with the awesome `react-intl`. I'd love to see https://github.com/andyearnshaw/Intl.js/pull/85 published.

**Comment by andyearnshaw** [comment]
@caridy was going to release a new version but he's been away.  I'm a little behind after recent contributions to the project so I'll try and get some time later this week to catch up and push a new release.

Ideally, I'd like to get the Travis CI problems resolved so I can ensure tests are passing and then we can get a more regular release schedule going.

**Comment by caridy** [comment]
guys, I'm just back from sabbatical, I'm sorry for the delay. We will get the release out this week :)

**Comment by caridy** [comment]
1.0.0-rc-1 is in NPM, help us to test it... and feedback...
